# Pytorch 介紹

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/taipeitechmmslab/MMSLAB-Pytorch/blob/master/Lab1.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/taipeitechmmslab/MMSLAB-Pytorch/blob/master/Lab1.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

In [1]:
import torch

Pytorch 的基本型態：

In [ ]:
# 產生一個常數c，為整數張量，預設不計算梯度，常用於輸入資料或標籤
c = torch.tensor(1)

# 產生一個變數 v，使用浮點數 (1.0) 並設定 requires_grad=True，代表變數v，後續可計算微分 (梯度)
v = torch.tensor(1.0, requires_grad=True)

print(c) 
print(v)

tensor(1)
tensor(1., requires_grad=True)


零階張量稱為標量。

In [3]:
x = torch.tensor(4)
print(x)  # 顯示Tensor 常數資訊，Shape=()表示標量，dtype=int32 表示整數
print("{} 階Tensor".format(x.dim()))  # 顯示Tensor 的維度

tensor(4)
0 階Tensor


一階張量稱為向量。

In [4]:
x = torch.tensor([1, 2, 3, 4, 5, 6]) 
print("{}階Tensor ".format(x.dim()))    # 顯示Tensor的維度

1階Tensor 


二階張量稱為矩陣。

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("{}階Tensor ".format(x.dim()))    # 顯示Tensor的維度

2階Tensor 


**Pytorch 基本運算：**

Import 必要套件

In [6]:
import numpy as np  # 載入 Numpy 數學函式庫
import torch        # 載入 PyTorch 核心深度學習函式庫

# 檢查PyTorch是否可用
print("PyTorch 是否可用:",torch.cuda.is_available())

PyTorch 是否可用: True


定義常數 Tensor

In [16]:
a = torch.tensor(3)    # 建立一個數值為 3 的 Tensor
b = torch.tensor(4)    # 建立一個數值為 4 的 Tensor

# 使用 .item() 提取並顯示純數值
print("a = {}".format(a.item()))
print("b = {}".format(b.item()))

a = 3
b = 4


檢查資料型態

In [17]:
print("a 的內容:", a)
print("a 的型態:", a.dtype)  # 預設整數通常為 torch.int64
print("a 的形狀:", a.shape)  # 零階張量的形狀為空陣列 torch.Size([])

a 的內容: tensor(3)
a 的型態: torch.int64
a 的形狀: torch.Size([])


基本運算

In [11]:
c = a + b
print("a + b = {}".format(c.item()))    # 顯示 a+b 的結果

d = a * b
print("a * b = {}".format(d.item()))    # 顯示 a*b 的結果

a + b = 7
a * b = 12


2D Tensor 的運算，可以混和 Tensor 和 Numpy 做運算

In [12]:
# 建立二維 PyTorch 張量，並且指定 dtype 為 float32
a = torch.tensor([[1., 2.], [3., 4.]], dtype=torch.float32)

# 建立一個 Numpy 陣列，並且 dtype 為 float32
b_np = np.array([[1., 0.], [2., 3.]], dtype=np.float32)

# 將 Numpy 陣列安全地轉換為 PyTorch Tensor
b = torch.from_numpy(b_np)

print("a 的維度: {}D Tensor".format(a.dim()))

# 矩陣元素相加
c = a + b
print("a + b = \n{}".format(c))

# 矩陣內積乘法 
d = torch.matmul(a, b)
print("a * b = \n{}".format(d))

a 的維度: 2D Tensor
a + b = 
tensor([[2., 2.],
        [5., 7.]])
a * b = 
tensor([[ 5.,  6.],
        [11., 12.]])


輸出的結果為 Tensor 格式，我們可以將它轉為 Numpy 格式

In [13]:
print("Numpy Array:\n{}".format(c.numpy()))

Numpy Array:
[[2. 2.]
 [5. 7.]]


計算梯度

In [14]:
# 宣告變數 w，並設定 requires_grad=True 讓 PyTorch 準備計算梯度
w = torch.tensor([[1.0]], requires_grad=True)

# 正向傳遞：PyTorch 會自動在背景記錄運算路徑
loss = w * w  # 損失函數為 w^2

# 反向傳遞計算梯度：∂loss/∂w = ∂(w^2)/∂w = 2w，∵w=1 ∴grad=2
loss.backward()

# 取得 w 的梯度數值
grad = w.grad
print(grad)

tensor([[2.]])


---
## torch.nn

下面將會介紹兩種最常使用的網路搭建方法：
- nn.Sequential (序列模型)
- Function API (函數式模型)

## nn.Sequential

nn.Sequential有兩種方法搭建，下面為分類問題範例：輸入為28x28 (拉平為784的一維向量)的影像，輸出為10 (分為十個類別)。



**Import 套件**

In [13]:
!pip install torchinfo
import torch
import torch.nn as nn
from torchinfo import summary

**Ex1：**

In [14]:
model1 = nn.Sequential(
    # 產生一個 Sequential 的 model
    # 全連接層 (Dense/Linear)，第一個參數是輸入尺寸，第二個參數是輸出尺寸
    nn.Linear(784, 64),
    nn.ReLU(),
    nn.Linear(64, 64),
    nn.ReLU(),
    # 最後一層會被當作是model的輸出層
    nn.Linear(64, 10),
    nn.Softmax(dim=1)
)

**Ex2：**

In [15]:
model = nn.Sequential()

# 每次 append 會增加一層網路到 model 中
model.append(nn.Linear(784, 64))
model.append(nn.ReLU())

model.append(nn.Linear(64, 64))
model.append(nn.ReLU())

model.append(nn.Linear(64, 10))
model.append(nn.Softmax(dim=1))

Sequential(
  (0): Linear(in_features=784, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): Softmax(dim=1)
)

顯示出剛剛搭建的網路

In [16]:
#顯示網路架構
summary(model1, input_size=(1, 784))

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 10]                   --
├─Linear: 1-1                            [1, 64]                   50,240
├─ReLU: 1-2                              [1, 64]                   --
├─Linear: 1-3                            [1, 64]                   4,160
├─ReLU: 1-4                              [1, 64]                   --
├─Linear: 1-5                            [1, 10]                   650
├─Softmax: 1-6                           [1, 10]                   --
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
Total mult-adds (M): 0.06
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.22
Estimated Total Size (MB): 0.22

## nn.Module

下方將會依序簡介幾種網路架構以及應用的場景：
- Single Input and Output Model：單輸入單輸出的網路。
- Multi Input Model：多輸入單輸出的網路。
- Multi Output Model：單輸入多輸出的網路。
- Multi Input and Output Model：多輸入多輸出的網路。



### Single Input and Output Model

In [21]:
class SingleIOModel(nn.Module):
    def __init__(self):
        super(SingleIOModel, self).__init__() # 繼承 nn.Module 的初始化
        # 定義所需的所有網路層 
        self.fc1 = nn.Linear(784, 64)
        self.fc2 = nn.Linear(64, 64)
        self.out = nn.Linear(64, 10)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        # 定義資料前向傳遞的流向
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.softmax(self.out(x))
        return x

model= SingleIOModel()
summary(model, input_size=(1, 784))

Layer (type:depth-idx)                   Output Shape              Param #
SingleIOModel                            [1, 10]                   --
├─Linear: 1-1                            [1, 64]                   50,240
├─ReLU: 1-2                              [1, 64]                   --
├─Linear: 1-3                            [1, 64]                   4,160
├─ReLU: 1-4                              [1, 64]                   --
├─Linear: 1-5                            [1, 10]                   650
├─Softmax: 1-6                           [1, 10]                   --
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
Total mult-adds (M): 0.06
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.22
Estimated Total Size (MB): 0.22

### Multi Input Model

In [24]:
class MultiInputModel(nn.Module):
    def __init__(self):
        super().__init__()
        # 影像特徵擷取分支
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5, stride=2)
        self.conv2 = nn.Conv2d(64, 32, kernel_size=5, stride=2)
        self.flatten = nn.Flatten()
        
        # 數值資訊分支
        self.fc_info = nn.Linear(1, 64)
        
        # 特徵融合後的網路層
        self.fc_combined = nn.Linear(26912 + 64, 64)
        self.output = nn.Linear(64, 1)
        self.relu = nn.ReLU()

    def forward(self, img_input, info_input):
        # 處理影像分支
        x1 = self.relu(self.conv1(img_input))
        x1 = self.relu(self.conv2(x1))
        x1 = self.flatten(x1)
        
        # 處理數值分支
        x2 = self.relu(self.fc_info(info_input))
        
        # 將兩種特徵在特徵維度 (dim=1) 上進行串接 (Concatenate)
        concat = torch.cat((x1, x2), dim=1)
        
        # 融合預測輸出
        out = self.relu(self.fc_combined(concat))
        out = self.output(out)
        return out

model = MultiInputModel()
summary(model, input_size=[(1, 3, 128, 128), (1, 1)])

Layer (type:depth-idx)                   Output Shape              Param #
MultiInputModel                          [1, 1]                    --
├─Conv2d: 1-1                            [1, 64, 62, 62]           4,864
├─ReLU: 1-2                              [1, 64, 62, 62]           --
├─Conv2d: 1-3                            [1, 32, 29, 29]           51,232
├─ReLU: 1-4                              [1, 32, 29, 29]           --
├─Flatten: 1-5                           [1, 26912]                --
├─Linear: 1-6                            [1, 64]                   128
├─ReLU: 1-7                              [1, 64]                   --
├─Linear: 1-8                            [1, 64]                   1,726,528
├─ReLU: 1-9                              [1, 64]                   --
├─Linear: 1-10                           [1, 1]                    65
Total params: 1,782,817
Trainable params: 1,782,817
Non-trainable params: 0
Total mult-adds (M): 63.51
Input size (MB): 0.20
Forward/backwar

### Multi Output Model

In [29]:
class MultiOutputModel(nn.Module):
    def __init__(self):
        super().__init__()
        # 共同的特徵萃取層
        self.conv1 = nn.Conv2d(1, 64, kernel_size=3)
        self.conv2 = nn.Conv2d(64, 64, kernel_size=3, stride=2)
        self.conv3 = nn.Conv2d(64, 64, kernel_size=3, stride=2)
        self.flatten = nn.Flatten()
        self.relu = nn.ReLU()
        
        # 多輸出分支 (假設攤平後尺寸為 1600)
        self.age_output = nn.Linear(1600, 1)
        self.gender_output = nn.Linear(1600, 1)

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        x = self.relu(self.conv3(x))
        x = self.flatten(x)
        
        # 網路分岔出兩個結果
        age = self.age_output(x)
        gender = self.gender_output(x)
        # PyTorch 允許多個輸出，直接 return 一個 Tuple
        return age, gender


model = MultiOutputModel()
summary(model, input_size=(1, 1, 28, 28))

Layer (type:depth-idx)                   Output Shape              Param #
MultiOutputModel                         [1, 1]                    --
├─Conv2d: 1-1                            [1, 64, 26, 26]           640
├─ReLU: 1-2                              [1, 64, 26, 26]           --
├─Conv2d: 1-3                            [1, 64, 12, 12]           36,928
├─ReLU: 1-4                              [1, 64, 12, 12]           --
├─Conv2d: 1-5                            [1, 64, 5, 5]             36,928
├─ReLU: 1-6                              [1, 64, 5, 5]             --
├─Flatten: 1-7                           [1, 1600]                 --
├─Linear: 1-8                            [1, 1]                    1,601
├─Linear: 1-9                            [1, 1]                    1,601
Total params: 77,698
Trainable params: 77,698
Non-trainable params: 0
Total mult-adds (M): 6.68
Input size (MB): 0.00
Forward/backward pass size (MB): 0.43
Params size (MB): 0.31
Estimated Total Size (MB): 0.75

### Multi Input and Output Model

In [31]:
class MultiInputOutputModel(nn.Module):
    def __init__(self):
        super().__init__()
        # 影像輸入分支
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3)
        self.conv2 = nn.Conv2d(64, 64, kernel_size=3, stride=2)
        self.conv3 = nn.Conv2d(64, 64, kernel_size=3, stride=2)
        self.flatten = nn.Flatten()
        
        # 數值輸入分支
        self.fc_info = nn.Linear(10, 64)
        
        # 三個獨立輸出分支 (假設結合後特徵長度為 245824 + 64)
        self.weather_out = nn.Linear(246080, 1)
        self.temp_out = nn.Linear(246080, 1)
        self.humidity_out = nn.Linear(246080, 1)
        self.relu = nn.ReLU()

    def forward(self, img, info):
        # 影像萃取
        x1 = self.relu(self.conv1(img))
        x1 = self.relu(self.conv2(x1))
        x1 = self.relu(self.conv3(x1))
        x1 = self.flatten(x1)
        
        # 數值萃取
        x2 = self.relu(self.fc_info(info))
        
        # 結合資訊
        concat = torch.cat((x1, x2), dim=1)
        
        # 分別預測三個輸出
        weather = self.weather_out(concat)
        temp = self.temp_out(concat)
        humidity = self.humidity_out(concat)
        
        return weather, temp, humidity

model = MultiInputOutputModel()
summary(model, input_size=[(1, 3, 256, 256), (1, 10)])

Layer (type:depth-idx)                   Output Shape              Param #
MultiInputOutputModel                    [1, 1]                    --
├─Conv2d: 1-1                            [1, 64, 254, 254]         1,792
├─ReLU: 1-2                              [1, 64, 254, 254]         --
├─Conv2d: 1-3                            [1, 64, 126, 126]         36,928
├─ReLU: 1-4                              [1, 64, 126, 126]         --
├─Conv2d: 1-5                            [1, 64, 62, 62]           36,928
├─ReLU: 1-6                              [1, 64, 62, 62]           --
├─Flatten: 1-7                           [1, 246016]               --
├─Linear: 1-8                            [1, 64]                   704
├─ReLU: 1-9                              [1, 64]                   --
├─Linear: 1-10                           [1, 1]                    246,081
├─Linear: 1-11                           [1, 1]                    246,081
├─Linear: 1-12                           [1, 1]                

---
## Dataset 與 DataLoader

### 基本操作

1.`TensorDataset`建立資料集

In [33]:
import torch
from torch.utils.data import TensorDataset, DataLoader, Dataset

x_data = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y_data = torch.tensor([0, 2, 4, 6, 8, 10, 12, 14, 16, 18])
dataset = TensorDataset(x_data, y_data)

# 顯示 Dataset 資訊
print("資料集總筆數:", len(dataset))
print("讀取第一筆資料:", dataset[0])

資料集總筆數: 10
讀取第一筆資料: (tensor(0), tensor(0))


2.`for loop`讀取資料：

In [34]:
for data1, data2 in dataset:
    print('x: {}, y: {}'.format(data1.item(), data2.item()))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10
x: 6, y: 12
x: 7, y: 14
x: 8, y: 16
x: 9, y: 18


3.建立自定義`Dataset`來轉換資料

In [35]:
class CustomMapDataset(Dataset):
    def __init__(self, size):
        self.size = size
        
    def __len__(self):
        return self.size
        
    def __getitem__(self, idx):
        # 在取出資料的瞬間進行轉換 (相當於 TF 的 lambda x: x*2)
        return torch.tensor(idx), torch.tensor(idx * 2)

map_dataset = CustomMapDataset(size=10)
print(map_dataset)

4.以字典方式為資料組件命名

In [36]:
class DictDataset(Dataset):
    def __init__(self, size):
        self.size = size
        
    def __len__(self):
        return self.size
        
    def __getitem__(self, idx):
        # 回傳帶有名稱的字典
        return {"x": torch.tensor(idx), "y": torch.tensor(idx * 2)}

dict_dataset = DictDataset(size=10)
print(dict_dataset)

5.`DataLoader`建立資料載入器

In [37]:
# 將剛才的字典資料集放入 DataLoader
dataloader = DataLoader(dict_dataset)

6.設定每一批（batch）讀取的資料量

In [44]:
dataloader = DataLoader(dict_dataset, batch_size=2)

for data in dataloader:
    print('x: {}, y: {}'.format(data['x'].numpy(), data['y'].numpy()))

x: [0 1], y: [0 2]
x: [2 3], y: [4 6]
x: [4 5], y: [ 8 10]
x: [6 7], y: [12 14]
x: [8 9], y: [16 18]


7.設定每batch讀取的數量

In [48]:
dataloader = DataLoader(dict_dataset, batch_size=5)

for i, data in enumerate(dataloader):
    if i >= 5: break
    print('x: {}, y: {}'.format(data['x'].numpy(), data['y'].numpy()))

x: [0 1 2 3 4], y: [0 2 4 6 8]
x: [5 6 7 8 9], y: [10 12 14 16 18]


8.`shuffle`：dataset資料 會被載入buffer中，並從buffer中隨機選取資料出來，取出資料產生的空位會從新的數據替補。而`buffer_size`是設定buffer大小，最好的設定是**大於**或**等於**整個dataset資料個個數。

In [40]:
dataloader = DataLoader(dict_dataset, batch_size=2, shuffle=True)

# 取前 3 個 batch 出來看看洗牌結果
for i, data in enumerate(dataloader):
    print('x: {}, y: {}'.format(data['x'].numpy(), data['y'].numpy()))
    if i == 2:
        break

x: [5 4], y: [10  8]
x: [3 9], y: [ 6 18]
x: [7 8], y: [14 16]


9.PyTorch的標準訓練流程中，我們是透過在最外層加上一個 「Epoch 迴圈」 來控制資料集要重複訓練幾次。每次進入新的迴圈，DataLoader 都會重新提供資料。

In [41]:
epochs = 2  

for epoch in range(epochs):
    print('-' * 20 + f' 第 {epoch+1} 次遍歷 (Epoch) ' + '-' * 20)
    for i, data in enumerate(dataloader):
        print('x: {}, y: {}'.format(data['x'].numpy(), data['y'].numpy()))
        # 每個 epoch取前 2 個 
        if i == 1: 
            break

-------------------- 第 1 次遍歷 (Epoch) --------------------
x: [3 7], y: [ 6 14]
x: [0 6], y: [ 0 12]
-------------------- 第 2 次遍歷 (Epoch) --------------------
x: [8 1], y: [16  2]
x: [4 9], y: [ 8 18]
